version: "3.3"
services:
  db:
    image: mysql:8.0
    container_name: rnApp-mySQL
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: rnApp-mySQL-db
      MYSQL_USER: rnAppUser
      # You can use whatever password you like
      MYSQL_PASSWORD: rnAppPrisma
      # Password for root access
      MYSQL_ROOT_PASSWORD: rnAppPrisma
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
